version: '2.3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  jupyter-cpu:
    image: kripa4rk/jupyter-notebook:cpu-0.6.0
    volumes:
      - ./../:/opt/notebooks
      - ./jupyter.sh:/root/jupyter.sh
    expose:
      - "8002"
    environment:
      - VIRTUAL_HOST=jupyter-cpu
      - VIRTUAL_PORT=8002
      - PORT=8002

  jupyter-gpu:
    image: kripa4rk/jupyter-notebook:gpu-0.6.0
    runtime: nvidia
    volumes:
      - ./../:/opt/notebooks
      - ./jupyter.sh:/root/jupyter.sh
    expose:
      - "8001"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - VIRTUAL_HOST=jupyter-gpu
      - VIRTUAL_PORT=8001
      - PORT=8001

# version: '2.3'
# services:
#   nvidia:
#     image: nvidia/cuda
#     runtime: nvidia
#     command: nvidia-smi