version: '2.3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    environment:
      - DEFAULT_HOST=jupyter-cpu   
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  jupyter-cpu:
    image: kripa4rk/jupyter-notebook:cpu-1.1.4
    volumes:
      - ./../:/opt/notebooks
      - ./jupyter.sh:/root/jupyter.sh
    expose:
      - "8002"
    environment:
      - VIRTUAL_HOST=jupyter-cpu
      - VIRTUAL_PORT=8002
      - PORT=8002

  jupyter-gpu:
    image: kripa4rk/jupyter-notebook:gpu-1.1.4
    runtime: nvidia
    volumes:
      - ./../:/opt/notebooks
      - ./jupyter.sh:/root/jupyter.sh
    expose:
      - "8001"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - VIRTUAL_HOST=jupyter-gpu
      - VIRTUAL_PORT=8001
      - PORT=8001

  ubuntu-server:
    image: bitnami/apache
    volumes:
      - ./../../:/app
    expose:
      - "8003"
    environment:
      - VIRTUAL_HOST=ubuntu-server
      - APACHE_HTTP_PORT_NUMBER=8003
      - VIRTUAL_PORT=8003

# version: '2.3'
# services:
#   nvidia:
#     image: nvidia/cuda
#     runtime: nvidia
#     command: nvidia-smi